import Head from 'next/head';
import Link from 'next/link';
export default function Home() {
  return (
    <>
      <Head>
        <title>Hello World</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Link href={'about'}>
          About
        </Link>
        <Link href={'profile'}>
          Profile
        </Link>
        <Link href={'products'}>
          Profile
        </Link>
        <h1>This is the Landing Page</h1>
      </main>
    </>
  )
}
